version: 2.1

jobs:
  build-base-image:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login -u $DOCKER_USERNAME -password $DOCKER_PASSWORD
      - run: cd base-builder && docker build . -t seemann/cpp-build-base:0.1.0
      - run: docker push seemann/cpp-build-base:0.1.0

workflows:
  version: 2
  build-and-push-on-commit:
    jobs:
      - build-base-image:
          context: DOCKER_HUB
