version: 2.1

parameters:
  start_at:
    type: string
    default: base

jobs:

  test:
    machine: true
    steps:
      - run: echo "<<pipeline.parameters.start_at>>"

  build-base-image:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: cd base-builder && docker build . -t seemann/cpp-build-base:0.1.0 --build-arg BOOST_VERSION=1.73.0 --build-arg BOOST_VERSION_NAME=1_73_0
      - run: docker push seemann/cpp-build-base:0.1.0

  build-cyng:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: cd cyng && docker build . -t seemann/cyng:0.1.0
      - run: docker push seemann/cyng:0.1.0

  build-crypto:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: cd crypto && docker build . -t seemann/crypto:0.1.0
      - run: docker push seemann/crypto:0.1.0

  build-node:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: cd node && docker build . -t seemann/node:0.1.0
      - run: docker push seemann/node:0.1.0

  build-master:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: cd master && docker build . -t seemann/master:0.1.0
      - run: docker push seemann/master:0.1.0

workflows:
  version: 2
  build-and-push-on-commit:
    jobs:
      - test
#      - build-base-image:
#          context: DOCKER_HUB
#      - build-cyng:
#          context: DOCKER_HUB
#          requires:
#            - build-base-image
#      - build-crypto:
#          context: DOCKER_HUB
#          requires:
#            - build-cyng
#      - build-node:
#          context: DOCKER_HUB
#          requires:
#            - build-crypto
#      - build-master:
#          context: DOCKER_HUB
#          requires:
#            - build-node
