version: 2.1

parameters:
  start_at:
    type: string
    default: base
  branch:
    type: string
    default: v0.8

commands:
  docker-login:
    steps:
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

jobs:

  test:
    machine: true
    steps:
      - run: echo "pre condition"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ node, <<pipeline.parameters.start_at>> ]
          steps:
            - run: echo "<<pipeline.parameters.start_at>>"

  build-base-image:
    machine: true
    steps:
      - run: echo "base check"
      - run: echo "<<pipeline.parameters.branch>>"
      - when:
          condition:
            equal: [ base, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f base-builder/Dockerfile . -t seemann/cpp-build-base:<<pipeline.parameters.branch>> --build-arg BOOST_VERSION=1.74.0 --build-arg BOOST_VERSION_NAME=1_74_0
            - run: docker push seemann/cpp-build-base:<<pipeline.parameters.branch>>

  build-oecp-image:
    machine: true
    steps:
      - run: echo "base check"
      - when:
          condition:
            equal: [ base, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f oecp-base/Dockerfile . -t seemann/oecp-base:<<pipeline.parameters.branch>> --build-arg BOOST_VERSION=1.74.0 --build-arg BOOST_VERSION_NAME=1_74_0
            - run: docker push seemann/oecp-base:<<pipeline.parameters.branch>>

  build-cyng:
    machine: true
    steps:
      - run: echo "cyng check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f cyng/Dockerfile . -t seemann/cyng:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>> --build-arg BRANCH=<<pipeline.parameters.branch>>
            - run: docker push seemann/cyng:<<pipeline.parameters.branch>>

  build-oecp-cyng:
    machine: true
    steps:
      - run: echo "cyng check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f oecp-cyng/Dockerfile . -t seemann/oecp-cyng:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>> --build-arg BRANCH=<<pipeline.parameters.branch>>
            - run: docker push seemann/oecp-cyng:<<pipeline.parameters.branch>>

  build-crypto:
    machine: true
    steps:
      - run: echo "crypto check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
              - equal: [ crypto, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f crypto/Dockerfile . -t seemann/crypto:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>> --build-arg BRANCH=master
            - run: docker push seemann/crypto:<<pipeline.parameters.branch>>

  build-oecp-crypto:
    machine: true
    steps:
      - run: echo "crypto check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
              - equal: [ crypto, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f oecp-crypto/Dockerfile . -t seemann/oecp-crypto:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>> --build-arg BRANCH=master
            - run: docker push seemann/oecp-crypto:<<pipeline.parameters.branch>>

  build-node:
    machine: true
    steps:
      - run: echo "node check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
              - equal: [ crypto, <<pipeline.parameters.start_at>> ]
              - equal: [ node, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f node/Dockerfile . -t seemann/node:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>> --build-arg BRANCH=<<pipeline.parameters.branch>>
            - run: docker push seemann/node:<<pipeline.parameters.branch>>

  build-oecp-node:
    machine: true
    steps:
      - run: echo "node check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
              - equal: [ crypto, <<pipeline.parameters.start_at>> ]
              - equal: [ node, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f oecp-node/Dockerfile . -t seemann/oecp-node:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>> --build-arg BRANCH=<<pipeline.parameters.branch>>
            - run: docker push seemann/oecp-node:<<pipeline.parameters.branch>>

  build-oecp-dist:
    machine: true
    steps:
      - run: echo "dist check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
              - equal: [ crypto, <<pipeline.parameters.start_at>> ]
              - equal: [ node, <<pipeline.parameters.start_at>> ]
              - equal: [ dist, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f oecp-dist/Dockerfile . -t seemann/oecp-dist:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>>
            - run: docker push seemann/oecp-dist:<<pipeline.parameters.branch>>

  build-dist:
    machine: true
    steps:
      - run: echo "dist check"
      - when:
          condition:
            or:
              - equal: [ base, <<pipeline.parameters.start_at>> ]
              - equal: [ cyng, <<pipeline.parameters.start_at>> ]
              - equal: [ crypto, <<pipeline.parameters.start_at>> ]
              - equal: [ node, <<pipeline.parameters.start_at>> ]
              - equal: [ dist, <<pipeline.parameters.start_at>> ]
          steps:
            - checkout
            - docker-login
            - run: docker build -f master/Dockerfile . -t seemann/master:<<pipeline.parameters.branch>> --build-arg BASE_TAG=<<pipeline.parameters.branch>>
            - run: docker push seemann/master:<<pipeline.parameters.branch>>

workflows:
  version: 2
  build-and-push-on-commit:
    jobs:
      - build-base-image:
          context: DOCKER_HUB
      - build-oecp-image:
          context: DOCKER_HUB
      - build-cyng:
          context: DOCKER_HUB
          requires:
            - build-base-image
      - build-oecp-cyng:
          context: DOCKER_HUB
          requires:
            - build-oecp-image
      - build-crypto:
          context: DOCKER_HUB
          requires:
            - build-cyng
      - build-oecp-crypto:
          context: DOCKER_HUB
          requires:
            - build-oecp-cyng
      - build-node:
          context: DOCKER_HUB
          requires:
            - build-crypto
      - build-oecp-node:
          context: DOCKER_HUB
          requires:
            - build-oecp-crypto
      - build-oecp-dist:
          context: DOCKER_HUB
          requires:
            - build-oecp-node
      - build-dist:
          context: DOCKER_HUB
          requires:
            - build-node
