name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker c++ Base image
      run: docker build . --file base-builder/Dockerfile --tag eemann/cpp-build-base:$(date +%s)
