name: Docker Image CI

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Start complete build
        run: |
          apk add curl
          apk add bash
          curl -u ${CIRCLECI_TOKEN}: -X POST https://circleci.com/api/v2/project/gh/mseemannn/segw-build/pipeline --header "Content-Type: application/json" -d '{"branch":"master"}'

