name: Start Docker Build on CircleCi

on:
  workflow_dispatch:
    inputs:
      start_at:
        description: 'Start the circleci workflow with base, node or crypto '
        required: true
        default: 'base'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Start complete build
        run: |
          apk add curl
          apk add bash
          echo '{"branch":"master", "start_at": "${{ github.event.inputs.start_at }}"}'
          curl -u ${{secrets.CIRCLECI_TOKEN}}: -X POST https://circleci.com/api/v2/project/gh/mseemann/segw-build/pipeline --header "Content-Type: application/json" -d '{ "parameters": { "start_at": "${{ github.event.inputs.start_at }}"}}'
